### ISSUE TITLE
Script not getting invoked

### ISSUE THREAD

**Issue by SilverFoxA** [lavary/crunz#127] opened 2018-08-12 12:00 UTC
I have implemented this library for one of my projects to have a scheduling feature. The web server running ubuntu 16.04 on LAMP stack.

Here's my implementation
      
      use Crunz\Schedule;
      
       //Initializing in constructor
       $this->schedule = new Schedule();

       $seconds = $param["timestamp"]/ 1000;
       $time = date("H:i Y-m-d", $seconds);

      //calling task script where $param is an array
       $this->schedule->run('/usr/bin/php /var/www/api/include/ops/cron/feeds.php',['json'=>json_encode($param)])       
                            ->on($time);

feeds.php

    $val = getopt('json');

The scheduler is not invoking the script

**Comment by PabloKowalczyk** [comment] 2018-08-12 13:02
Hello,
i think that your usage of `on` is wrong. Do you intend to run this script every minute?

**Comment by SilverFoxA** [comment] 2018-08-12 15:16
No, I intend to use it on a day say `13th August 2018` at `16:10`

**Comment by PabloKowalczyk** [comment] 2018-08-12 16:14
Does it worked with `->on('13:30 2016-03-01')`?

**Comment by SilverFoxA** [comment] 2018-08-12 16:35
Don't you think this time frame has passed? 

Here is what I have passed `17:19 2018-08-12`

**Comment by PabloKowalczyk** [comment] 2018-08-12 16:45
Just example :) Did you configured `timezone` in your YAML config file?

**Comment by SilverFoxA** [comment] 2018-08-12 17:50
yes, I have specified the time zone to be `Asia/Kolkata`, was wondering is there any other means using which we can debug this use case?

I'm yet to check the server timestamp. Assuming that will give some hint.

**Comment by PabloKowalczyk** [comment] 2018-08-15 14:49
I have done some tests. I specified `Europe/Warsaw` timezone and below script works as expected:
```php
<?php

use Crunz\Schedule;
$schedule = new Schedule();

$event = $schedule->run('echo Hello');
$event->on('16:40 2018-08-15'); // Of course use current date for tests
$event->description('On test');

return $schedule;
```
Make sure you are using correct timezone and `on` method should works as expected, also please notice that passing timestamp to `on` method could lead to some weird parse output as year 1534 or day 344 - https://3v4l.org/eHh4F

**Comment by cjeraldop** [comment] 2018-08-31 23:04
I got the same error :-1:  

@PabloKowalczyk
I tested your example and doesn't works. I executed your example and got the same error as @SilverFoxA

> root@desa2:/var/www/ficr/# vendor/bin/crunz schedule:run
> No event is due!
> **[2018-08-31 19:54:44] crunz.ERROR: 19:54:44 2018-08-31 [] []**
> 19:54:44 2018-08-31root@desa2:/var/www/ficr# 
> 


It only works when I use the timer every one minute.

**Comment by PabloKowalczyk** [comment] 2018-09-01 07:33
@cjeraldop it is very weird. What version of Crunz did you use and could you paste your task and config?

**Comment by PabloKowalczyk** [comment] 2019-01-26 06:45
@SilverFoxA @cjeraldop seems that this issue is possible duplicate of https://github.com/lavary/crunz/issues/176, if version `v1.11.0` do not solve your problems feel free to open new issue.

**Closed by PabloKowalczyk** 2019-01-26 06:45 UTC
