### ISSUE TITLE
Undefined index: year in vendor/lavary/crunz/src/Event.php on line 370

### ISSUE THREAD

**Issue by krlitus** [lavary/crunz#41] opened 2016-11-30 18:56 UTC
This error occurs when using on method in 'Running Events at Certain Times'

```php    
    /**
     * Position of cron fields
     *
     * @var array
     */
    protected $fieldsPosition = [
        'minute' => 1,
        'hour'   => 2,
        'day'    => 3,
        'month'  => 4,
        'week'   => 5,
    ];

    /**
     * Schedule the event to run on a certain date
     *
     * @param  string  $date
     *
     * @return $this
     */
    public function on($date)
    {
        
        $date     = date_parse($date);
        $segments = array_only($date, array_flip($this->fieldsPosition));

        if ($date['year']) {
 
            $this->skip(function () use ($segments) {
                return (int) date('Y') != $segments['year'];
            });

        }
                
        foreach ($segments as $key => $value) {   
            if ($value != false) {                
                $this->spliceIntoPosition($this->fieldsPosition[$key], (int) $value);
            }
        }

        return $this;          
    }
```

Apparently missing the position for the year in the attribute 'fieldsPosition'.

**Comment by MoatazGitHub** [comment] 2018-03-12 19:11
How can I fix this issue ?

**Comment by PabloKowalczyk** [comment] 2018-04-21 10:42
@krlitus could you provide date that causes this issue?

**Comment by mindcreations** [comment] 2018-06-12 10:54
Experienced this problem today while trying on() method. The problem is caused by $segments['year'] in this line:
```php
return (int) date('Y') != $segments['year'];
```
To fix this I think is enough to replace $segments with $date the fixed code will look like:
```php
            $this->skip(function () use ($date) {
                return (int) date('Y') != $date['year'];
            });
```
I'll arrange a push request...

**Comment by PabloKowalczyk** [comment] 2018-06-15 19:00
Fixed in https://github.com/lavary/crunz/pull/118. Thanks guys.

**Closed by PabloKowalczyk** 2018-06-15 19:00 UTC
Labels: bug
