### ISSUE TITLE
Cannot Open Crunz File in vendor/bin

### ISSUE THREAD

**Issue by ryleeferguson** [lavary/crunz#145] opened 2018-10-03 02:49 UTC
**Crunz version**: 1.10.1

**PHP version**: 7.1.9

**Operating system type and version**: CloudLinux Server release 6.10 (Vladimir Lyakhov)

**Description**  
Possible issue with the symbolic link created in `vendor/bin/crunz`
After updating to this version I realised none of my scripts were running.
When attempting to run manually, using the `schedule:run` syntax, I received this error:
`Could not open input file: {path_to_public_html}/vendor/bin/crunz`

I'm able to see the file when using `ls vendor/bin` so that's no the issue

So I decided to revert back to a previous version of the `crunz` file and it is working once again.
I believe the content of the reverted file is simply `../lavary/crunz/crunz`

**How to reproduce**  
Upgrade to latest version and attempt to run

**Possible Solution**  
I noticed the file added 9 more lines, possibly a syntax issue?

**Comment by PabloKowalczyk** [comment] 2018-10-03 16:42
Hello,
it is very weird bug, i did some upgrades of Crunz lately and didn't experienced this problem.
To make sure that issue is related to Crunz not to Composer, could you delete all `vendor`s (`rm -rf vendor`) and reinstall dependencies (`composer install`)?

**Comment by PabloKowalczyk** [comment] 2019-01-26 06:47
Possible duplicate of https://github.com/lavary/crunz/issues/176, fell free to open new issue if version `v1.11.0` do not solve your problems.

**Closed by PabloKowalczyk** 2019-01-26 06:47 UTC
