### ISSUE TITLE
Long running closure blocks other tasks

### ISSUE THREAD

**Issue by esetnik** [lavary/crunz#260] opened 2019-10-29 14:21 UTC
**Crunz version**: x.y.z
v2.0.2
**PHP version**: x.y.z
v7.3.11
**Operating system type and version**:
docker php:7.3-fpm
**Description**  
Running a long running task in closure blocks other tasks from executing.

**How to reproduce** 
LongRunningTasks.php
```php
$event = $schedule->run(function () {
        while (true) {
            echo 'output';
        }

})
->description('long-running-task')
->preventOverlapping();
$event
    ->everyMinute();

$event2 = $schedule->run(function () {
            echo 'another task';
})
->description('long-running-task')
->preventOverlapping();

$event2
    ->everyMinute();

return $schedule;
```

**Possible Solution**  
The lavary implementation looks similar to the symphony process implementation for running processes asynchronously so I'm not sure why it doesn't work.

https://symfony.com/doc/current/components/process.html
```php
$process = new Process(['ls', '-lsa']);
$process->start();

while ($process->isRunning()) {
    // waiting for process to finish
}

echo $process->getOutput();
```
**Additional context**

**Comment by PabloKowalczyk** [comment] 2019-10-29 16:34
Did you mean, run long running task in one terminal, then try to run Crunz again with another terminal and other tasks from long running file will not be run?

**Comment by PabloKowalczyk** [comment] 2019-10-29 17:34
Sorry, I mean "is it a correct way to reproduce the issue?", but looks like it is.

**Comment by PabloKowalczyk** [comment] 2019-11-17 08:44
Hey @esetnik, could you run Crunz with `-vvv` option?

**Comment by PabloKowalczyk** [comment] 2019-11-17 15:19
Interesting issue, seems that there were two errors (both fixed). First, as described in https://github.com/lavary/crunz/pull/264 version `v2.x` changes behavior of Closures' return value, so Closures from your example were failing and this leads to second bug, locks were not released on task's error (fixed in #261). Test  it with `v2.0.4` release.

Thanks @esetnik.

**Comment by esetnik** [comment] 2019-11-17 16:17
Thank you for taking the time to look into this issue for me. I will update you once I get a chance to test this out. The solution seems reasonable and explains the odd behavior I was seeing.

**Comment by PabloKowalczyk** [comment] 2019-12-08 07:14
@esetnik what about this issue? Could it be closed?

**Comment by esetnik** [comment] 2019-12-09 19:02
@PabloKowalczyk I apologize for the delay in getting back to you. This issue appears to be fixed now. Although it should be noted that a long running task which outputs to the console will eventually run out of memory due to #152 as far as I know.

**Comment by PabloKowalczyk** [comment] 2019-12-12 06:27
#152 is a different topic, as a quick fix you could suppress any output from your "long running task" - should help.

I'm closing this issue, thanks @esetnik.

**Closed by PabloKowalczyk** 2019-12-12 06:27 UTC
Labels: bug
